apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nzv5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/nbe-e2e-yffx-tenant/integ-app-yhxp/hacbs-test-project-nzv5@sha256:fe301dd303a23eadca7d878fb8f61e2107eb1a51eefd9192cccc322212166137
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
